# Generated by Django 4.0.6 on 2022-07-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledword',
            name='text',
            field=models.TextField(unique=True),
        ),
    ]
